window.VERTICAL_CONFIG = {
  appName: 'Teaspoon',
  logoHTML: 'Teaspoon<span>.</span>',
  tagline: 'the estimator for the gigging baker',
  storageKey: 'teaspoon_v1',

  colors: {
    bg: '#FDF6EE',
    surface: '#FFFCF8',
    surface2: '#F2E8DA',
    border: '#E0D0BC',
    text: '#2A1F14',
    'text-muted': '#7A6555',
    accent: '#9B3A1A',
    'accent-light': '#F5E6DF',
    accent2: '#3A6B3A',
    'accent2-light': '#DFF0DF',
  },

  emptyIcons: {
    ingredients: '🧁',
    recipes: '📋',
    menus: '📁',
  },

  defaultState: {
    ingredients: [
      { id: 1,  name: 'All-Purpose Flour',     uom: 'cup',  size: 18.9, price: 1.97 },
      { id: 2,  name: 'Bread Flour',            uom: 'cup',  size: 18.9, price: 2.48 },
      { id: 3,  name: 'Whole Wheat Flour',      uom: 'cup',  size: 18.9, price: 2.98 },
      { id: 4,  name: 'Cake Flour',             uom: 'cup',  size: 18.9, price: 3.48 },
      { id: 5,  name: 'Granulated Sugar',       uom: 'cup',  size: 8.5,  price: 2.97 },
      { id: 6,  name: 'Brown Sugar (Light)',    uom: 'cup',  size: 3.5,  price: 1.94 },
      { id: 7,  name: 'Brown Sugar (Dark)',     uom: 'cup',  size: 3.5,  price: 1.94 },
      { id: 8,  name: 'Powdered Sugar',         uom: 'cup',  size: 7,    price: 1.97 },
      { id: 9,  name: 'Honey',                  uom: 'tbsp', size: 24,   price: 4.98 },
      { id: 10, name: 'Unsalted Butter',        uom: 'tbsp', size: 32,   price: 5.98 },
      { id: 11, name: 'Salted Butter',          uom: 'tbsp', size: 32,   price: 5.98 },
      { id: 12, name: 'Vegetable Oil',          uom: 'cup',  size: 6,    price: 3.57 },
      { id: 13, name: 'Coconut Oil',            uom: 'tbsp', size: 28,   price: 5.48 },
      { id: 14, name: 'Shortening',             uom: 'cup',  size: 6,    price: 3.98 },
      { id: 15, name: 'Whole Milk',             uom: 'cup',  size: 16,   price: 4.28 },
      { id: 16, name: 'Buttermilk',             uom: 'cup',  size: 4,    price: 2.48 },
      { id: 17, name: 'Heavy Cream',            uom: 'cup',  size: 2,    price: 3.98 },
      { id: 18, name: 'Sour Cream',             uom: 'cup',  size: 2,    price: 2.48 },
      { id: 19, name: 'Cream Cheese',           uom: 'oz',   size: 8,    price: 2.98 },
      { id: 20, name: 'Large Eggs',             uom: 'egg',  size: 12,   price: 4.98 },
      { id: 21, name: 'Baking Powder',          uom: 'tsp',  size: 55,   price: 1.98 },
      { id: 22, name: 'Baking Soda',            uom: 'tsp',  size: 96,   price: 0.92 },
      { id: 23, name: 'Active Dry Yeast',       uom: 'tsp',  size: 21,   price: 2.98 },
      { id: 24, name: 'Instant Yeast',          uom: 'tsp',  size: 21,   price: 2.98 },
      { id: 25, name: 'Salt',                   uom: 'tsp',  size: 400,  price: 1.28 },
      { id: 26, name: 'Vanilla Extract',        uom: 'tsp',  size: 12,   price: 4.98 },
      { id: 27, name: 'Almond Extract',         uom: 'tsp',  size: 12,   price: 3.98 },
      { id: 28, name: 'Lemon Zest',             uom: 'tsp',  size: 4,    price: 0.59 },
      { id: 29, name: 'Semi-Sweet Choc Chips',  uom: 'cup',  size: 2,    price: 3.58 },
      { id: 30, name: 'Cocoa Powder',           uom: 'cup',  size: 3,    price: 2.98 },
      { id: 31, name: 'Dark Chocolate Chips',   uom: 'cup',  size: 2,    price: 3.98 },
      { id: 32, name: 'Cinnamon',               uom: 'tsp',  size: 60,   price: 2.48 },
      { id: 33, name: 'Nutmeg',                 uom: 'tsp',  size: 30,   price: 2.48 },
      { id: 34, name: 'Ginger (ground)',        uom: 'tsp',  size: 30,   price: 2.48 },
      { id: 35, name: 'Cloves (ground)',        uom: 'tsp',  size: 30,   price: 2.48 },
      { id: 36, name: 'Rolled Oats',            uom: 'cup',  size: 13,   price: 3.98 },
      { id: 37, name: 'Cream of Tartar',        uom: 'tsp',  size: 45,   price: 2.48 },
      { id: 38, name: 'Cornstarch',             uom: 'tbsp', size: 55,   price: 1.98 },
      { id: 39, name: 'Raisins',                uom: 'cup',  size: 4,    price: 2.98 },
      { id: 40, name: 'Walnuts (chopped)',      uom: 'cup',  size: 2,    price: 3.98 },
    ],
    recipes: [
      { id: 1, name: 'Chocolate Chip Cookies', desc: 'Classic batch — yields ~36 cookies',
        ingredients: [{ ingId: 1, amount: 2.25 },{ ingId: 22, amount: 1 },{ ingId: 25, amount: 1 },{ ingId: 10, amount: 16 },{ ingId: 5, amount: 0.75 },{ ingId: 6, amount: 0.75 },{ ingId: 20, amount: 2 },{ ingId: 26, amount: 2 },{ ingId: 29, amount: 2 }] },
      { id: 2, name: 'Banana Bread', desc: 'One 9x5 loaf — 10 slices',
        ingredients: [{ ingId: 1, amount: 1.5 },{ ingId: 22, amount: 1 },{ ingId: 25, amount: 0.5 },{ ingId: 10, amount: 8 },{ ingId: 5, amount: 0.75 },{ ingId: 20, amount: 2 },{ ingId: 26, amount: 1 },{ ingId: 15, amount: 0.25 }] },
      { id: 3, name: 'Classic Brownies', desc: 'One 9x13 pan — 24 bars',
        ingredients: [{ ingId: 10, amount: 16 },{ ingId: 5, amount: 2 },{ ingId: 20, amount: 4 },{ ingId: 26, amount: 2 },{ ingId: 30, amount: 1 },{ ingId: 1, amount: 1 },{ ingId: 25, amount: 0.5 },{ ingId: 21, amount: 0.5 }] },
      { id: 4, name: 'Oatmeal Raisin Cookies', desc: 'Classic batch — yields ~48 cookies',
        ingredients: [{ ingId: 10, amount: 16 },{ ingId: 5, amount: 0.75 },{ ingId: 6, amount: 0.75 },{ ingId: 20, amount: 2 },{ ingId: 26, amount: 1 },{ ingId: 1, amount: 1.5 },{ ingId: 22, amount: 1 },{ ingId: 32, amount: 1 },{ ingId: 25, amount: 1 },{ ingId: 36, amount: 3 },{ ingId: 39, amount: 1 }] },
      { id: 5, name: 'Cream Cheese Frosting', desc: 'Frosts one 9-inch layer cake',
        ingredients: [{ ingId: 19, amount: 8 },{ ingId: 10, amount: 8 },{ ingId: 8, amount: 4 },{ ingId: 26, amount: 1 }] },
    ],
    menus: [
      { id: 1, name: 'Saturday Farmers Market',
        recipes: [{ recipeId: 1, qty: 4 },{ recipeId: 2, qty: 6 },{ recipeId: 3, qty: 2 },{ recipeId: 4, qty: 3 }] }
    ],
    nextIngId: 41, nextRecId: 6, nextMenuId: 2,
  },
};
